name: mafabi_ml_engine
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - google-genai
    - python-dotenv
    - halo
    - pdfplumber
    - python-multipart